[package]
name = "xserial-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
serialport = { workspace = true }
tokio-serial = { workspace = true }
bytes = { workspace = true }
nom = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
hex = "0.4"
